version: "3.8"
x-server-config: &server-config
  ports:
    - "${API_PORT}:${API_PORT}"
  links:
    - mongo
    - redis-server
  volumes:
    - ./src:/usr/app/src

services:
  server:
    <<: *server-config
    build:
      context: .
      target: "production"
  dev-server:
    <<: *server-config
    build:
      context: .
      target: "development"
  mongo:
    image: mongo:4.2
    ports:
      - "27018:27017"
  redis-server:
    image: "redis"
    ports:
      - "6380:6379"
