export const colors = [
  { label: "Abricot", value: "#E67E30" },
  { label: "Acajou", value: "#88421D" },
  { label: "Aigue-marine", value: "#79F8F8" },
  { label: "Alezan", value: "#A76726" },
  { label: "Amande", value: "#82C46C" },
  { label: "Amarante", value: "#91283B" },
  { label: "Ambre", value: "#F0C300" },
  { label: "Améthyste", value: "#884DA7" },
  { label: "Anthracite", value: "#303030" },
  { label: "Aquilain", value: "#AD4F09" },
  { label: "Argent", value: "#FFFFFF" },
  { label: "Aubergine", value: "#370028" },
  { label: "Auburn", value: "#9D3E0C" },
  { label: "Aurore", value: "#FFCB60" },
  { label: "Avocat", value: "#568203" },
  { label: "Azur", value: "#007FFF" },
  { label: "Baillet", value: "#AE642D" },
  { label: "Basané", value: "#8B6C42" },
  { label: "Beurre", value: "#F0E36B" },
  { label: "Bis", value: "#766F64" },
  { label: "Bisque", value: "#FFE4C4" },
  { label: "Bistre", value: "#856D4D" },
  { label: "Bitume", value: "#4E3D28" },
  { label: "Blanc cassé", value: "#FEFEE2" },
  { label: "Blanc lunaire", value: "#F4FEFE" },
  { label: "Blé", value: "#E8D630" },
  { label: "Bleu acier", value: "#3A8EBA" },
  { label: "Bleuet", value: "#5472AE" },
  { label: "Bleu canard", value: "#048B9A" },
  { label: "Bleu céleste", value: "#26C4EC" },
  { label: "Bleu charrette", value: "#8EA2C6" },
  { label: "Bleu ciel", value: "#77B5FE" },
  { label: "Bleu de cobalt", value: "#22427C" },
  { label: "Bleu électrique", value: "#2C75FF" },
  { label: "Bleu givré", value: "#80D0D0" },
  { label: "Bleu marine", value: "#03224C" },
  { label: "Bleu nuit", value: "#0F056B" },
  { label: "Bleu outremer", value: "#004787" },
  { label: "Bleu paon", value: "#067790" },
  { label: "Bleu persan", value: "#4E63CE" },
  { label: "Bleu pétrole", value: "#1D4851" },
  { label: "Bleu de France", value: "#318CE7" },
  { label: "Bleu turquin", value: "#425B8A" },
  { label: "Blond vénitien", value: "#E7A854" },
  { label: "Blond", value: "#E2BC74" },
  { label: "Bouton d'or", value: "#FCDC12" },
  { label: "Brique", value: "#842E1B" },
  { label: "Bronze", value: "#614E1A" },
  { label: "Brou de noix", value: "#3F2204" },
  { label: "Caca d'oie", value: "#CDCD0D" },
  { label: "Cacao", value: "#614B3A" },
  { label: "Cachou", value: "#2F1B0C" },
  { label: "Cæruleum", value: "#357AB7" },
  { label: "Café", value: "#462E01" },
  { label: "Café au lait", value: "#785E2F" },
  { label: "Cannelle", value: "#7E5835" },
  { label: "Capucine", value: "#FF5E4D" },
  { label: "Caramel", value: "#7E3300" },
  { label: "Carmin", value: "#960018" },
  { label: "Carotte", value: "#F4661B" },
  { label: "Chamois", value: "#D0C07A" },
  { label: "Chartreuse", value: "#7FFF00" },
  { label: "Châtain", value: "#8B6C42" },
  { label: "Chaudron", value: "#85530F" },
  { label: "Chocolat", value: "#5A3A22" },
  { label: "Cinabre", value: "#DB1702" },
  { label: "Citrouille", value: "#DF6D14" },
  { label: "Coquille d'œuf", value: "#FDE9E0" },
  { label: "Corail", value: "#E73E01" },
  { label: "Cramoisi", value: "#DC143C" },
  { label: "Cuisse de nymphe", value: "#FEE7F0" },
  { label: "Cuivre", value: "#B36700" },
  { label: "Cyan", value: "#2BFAFA" },
  { label: "Écarlate", value: "#ED0000" },
  { label: "Écru", value: "#FEFEE0" },
  { label: "Émeraude", value: "#00815F" },
  { label: "Fauve", value: "#AD4F09" },
  { label: "Flave", value: "#E6E697" },
  { label: "Fraise", value: "#BF3030" },
  { label: "Fraise écrasée", value: "#A42424" },
  { label: "Framboise", value: "#C72C48" },
  { label: "Fuchsia", value: "#FD3F92" },
  { label: "Fumée", value: "#BBD2E1" },
  { label: "Garance", value: "#EE1010" },
  { label: "Glauque", value: "#649B88" },
  { label: "Glycine", value: "#C9A0DC" },
  { label: "Grège", value: "#BBAE98" },
  { label: "Grenadine", value: "#E9383F" },
  { label: "Grenat", value: "#6E0B14" },
  { label: "Gris acier", value: "#AFAFAF" },
  { label: "Gris de Payne", value: "#677179" },
  { label: "Gris fer", value: "#7F7F7F" },
  { label: "Gris perle", value: "#CECECE" },
  { label: "Gris souris", value: "#9E9E9E" },
  { label: "Groseille", value: "#CF0A1D" },
  { label: "Gueules", value: "#E21313" },
  { label: "Héliotrope", value: "#DF73FF" },
  { label: "Incarnat", value: "#FF6F7D" },
  { label: "Indigo", value: "#791CF8" },
  { label: "Indigo", value: "#2E006C" },
  { label: "Isabelle", value: "#FEA777" },
  { label: "Jaune canari", value: "#E7F00D" },
  { label: "Jaune citron", value: "#F7FF3C" },
  { label: "Jaune d'or", value: "#EFD807" },
  { label: "Jaune de cobalt", value: "#FDEE00" },
  { label: "Jaune de Mars", value: "#EED153" },
  { label: "Jaune de Naples", value: "#FFF0BC" },
  { label: "Jaune impérial", value: "#FFE436" },
  { label: "Jaune mimosa", value: "#FEF86C" },
  { label: "Lapis-lazuli", value: "#26619C" },
  { label: "Lavallière", value: "#8F5922" },
  { label: "Lavande", value: "#9683EC" },
  { label: "Lie de vin", value: "#AC1E44" },
  { label: "Lilas", value: "#B666D2" },
  { label: "Vert citron", value: "#9EFD38" },
  { label: "Lin", value: "#FAF0E6" },
  { label: "Magenta", value: "#FF00FF" },
  { label: "Maïs", value: "#FFDE75" },
  { label: "Malachite", value: "#1FA055" },
  { label: "Mandarine", value: "#FEA347" },
  { label: "Marron", value: "#582900" },
  { label: "Mastic", value: "#B3B191" },
  { label: "Mauve", value: "#D473D4" },
  { label: "Menthe", value: "#16B84E" },
  { label: "Moutarde", value: "#C7CF00" },
  { label: "Nacarat", value: "#FC5D5D" },
  { label: "Nankin", value: "#F7E269" },
  { label: "Noisette", value: "#955628" },
  { label: "Ocre jaune", value: "#DFAF2C" },
  { label: "Ocre rouge", value: "#DD985C" },
  { label: "Olive", value: "#708D23" },
  { label: "Or", value: "#FFD700" },
  { label: "Orange brûlé", value: "#CC5500" },
  { label: "Orchidée", value: "#DA70D6" },
  { label: "Orpiment", value: "#FCD21C" },
  { label: "Paille", value: "#FEE347" },
  { label: "Parme", value: "#CFA0E9" },
  { label: "Pelure d'oignon", value: "#D58490" },
  { label: "Pervenche", value: "#CCCCFF" },
  { label: "Pistache", value: "#BEF574" },
  { label: "Poil de chameau", value: "#B67823" },
  { label: "Coquelicot", value: "#C60800" },
  { label: "Pourpre", value: "#9E0E40" },
  { label: "Prasin", value: "#4CA66B" },
  { label: "Prune", value: "#811453" },
  { label: "Puce", value: "#4E1609" },
  { label: "Rose Mountbatten", value: "#997A8D" },
  { label: "Rouge anglais", value: "#F7230C" },
  { label: "Rouge cardinal", value: "#B82010" },
  { label: "Rouge cerise", value: "#BB0B0B" },
  { label: "Rouge d'Andrinople", value: "#A91101" },
  { label: "Rouge de Falun", value: "#801818" },
  { label: "Rouge feu", value: "#FF4901" },
  { label: "Rouge indien", value: "#CD5C5C" },
  { label: "Rouge sang", value: "#850606" },
  { label: "Rouge tomette", value: "#AE4A34" },
  { label: "Rouille", value: "#985717" },
  { label: "Roux", value: "#AD4F09" },
  { label: "Rubis", value: "#E0115F" },
  { label: "Sable", value: "#E0CDA9" },
  { label: "Safre", value: "#0131B4" },
  { label: "Sang de bœuf", value: "#730800" },
  { label: "Sanguine", value: "#850606" },
  { label: "Saphir", value: "#0131B4" },
  { label: "Sarcelle", value: "#008080" },
  { label: "Saumon", value: "#F88E55" },
  { label: "Sépia", value: "#AE8964" },
  { label: "Sinople", value: "#149414" },
  { label: "Smalt", value: "#003399" },
  { label: "Soufre", value: "#FFFF6B" },
  { label: "Tabac", value: "#9F551E" },
  { label: "Taupe", value: "#463F32" },
  { label: "Terre d'ombre", value: "#926D27" },
  { label: "Tomate", value: "#DE2916" },
  { label: "Topaze", value: "#FAEA73" },
  { label: "Tourterelle", value: "#BBACAC" },
  { label: "Turquoise", value: "#25FDE9" },
  { label: "Vanille", value: "#E1CE9A" },
  { label: "Vermeil", value: "#FF0921" },
  { label: "Vermillon", value: "#DB1702" },
  { label: "Vert bouteille", value: "#096A09" },
  { label: "Vert céladon", value: "#83A697" },
  { label: "Vert d'eau", value: "#B0F2B6" },
  { label: "Vert de chrome", value: "#18391E" },
  { label: "Vert-de-gris", value: "#95A595" },
  { label: "Vert de Hooker", value: "#1B4F08" },
  { label: "Vert émeraude", value: "#366735" },
  { label: "Vert épinard", value: "#175732" },
  { label: "Vert impérial", value: "#00561B" },
  { label: "Vert lichen", value: "#85C17E" },
  { label: "Vert olive", value: "#556B2F" },
  { label: "Vert perroquet", value: "#3AF24B" },
  { label: "Vert poireau", value: "#4CA66B" },
  { label: "Vert pomme", value: "#34C924" },
  { label: "Vert prairie", value: "#57D53B" },
  { label: "Vert printemps", value: "#00FF7F" },
  { label: "Vert sapin", value: "#095228" },
  { label: "Vert sauge", value: "#689D71" },
  { label: "Vert tilleul", value: "#A5D152" },
  { label: "Vert Véronèse", value: "#5A6521" },
  { label: "Violet", value: "#8806CE" },
  { label: "Violet d'évêque", value: "#723E64" },
  { label: "Viride", value: "#40826D" },
  { label: "Zinzolin", value: "#6C0277" },
];
